baseURL = "https://Jacklee504.github.io/hugo-app/"
languageCode = "en-us"
title = "My Hugo Site"
theme = "ananke"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
